env:
  global:
    - GITHUB_USERNAME=joberstein
    - RELEASE_TYPE=patch
    - IS_MASTER="$(if [[ $TRAVIS_BRANCH == 'master' ]]; then true; else echo false; fi)"
    - CHANGELIST="$(if $IS_MASTER; then echo ''; else echo '-SNAPSHOT'; fi)"

    # GITHUB TOKEN (Package Management)
    - secure: LIbB4L7syWl50gMtVnoZWwbvkv9vlNVAoXLFTPwAMYPaqrqyYcMKXdPOMdeFyV8Gbm+Dzvv94q8e1sWpLpkYfM4oHO8iWb7ta1k6h6D8GZC7Kb84HbPjnp626VOFWKg2cpUL5MUCUSRfOu7VYUOnPijxkT+g7D863kNCzgHE++P4K89M3Y+F2LpAiYfTT0jOGyXT7CsioiefkbHF2TMLtAAVJ6Kb0iEWI9JrA5/PFj6UiFk2XJlBfhYhVLomxvDZvvN9cEvWNzqN8bzwQ9z/gL8LEluU63sInFAdAO+6pmVV06rAdRMlspl19H+Jfe3NPHzBztC0iJLb+JJM8SImTIIpx7zB5Vtl9ElB0GLW7sl5Y+eYhGwtDlmPygE6sPaiKEezJPW+k+pGK9THDH0RRUWodDgpe4H1XLYrh9TDPMlETGrb5wj7ikG4ADUj85dKuNkXqSPGN7Mv4iVuYMtQE+ungTDWKglrtnLyGbUi49YD9mBOnKAdmXpQszJUkwuErBvF6UAQ8XB02mf4jtQ3zQRBjiO3I1heX1VL3szsv/NkETMjv6G24VIKIOIN+qWo+bMNI6QCrmJoRePa4wwjUYWHuCbsGS5XYCJs3KQru0qlYuchptFULmu9kzcZoAVCA/3zT5W0DRp/AfnGT0VGG5wRt6slLabTcFnUJiIt7Kg=

jobs:
  include:
    - if: tag IS blank
      language: java
      jdk: oraclejdk11
      cache:
        directories:
          - "$HOME/.m2"
      install:
        - nvm install lts/*
      before_script:
        - echo $IS_MASTER
        - echo $CHANGELIST
        - echo $TRAVIS_COMMIT_MESSAGE
        - git remote add origin git@github.com:joberstein/mbta-api-service.git
        - CURRENT_VERSION="$(git describe origin/master --tags)"
        - echo $CURRENT_VERSION
      script:
        - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ ^Major:.* ]]; then RELEASE_TYPE=major; fi
        - if [[ "$TRAVIS_COMMIT_MESSAGE" =~ ^Minor:.* ]]; then RELEASE_TYPE=minor; fi
        - echo $RELEASE_TYPE
        - NEW_VERSION="$(npx semver -i $RELEASE_TYPE $CURRENT_VERSION)"
        - echo $NEW_VERSION
      deploy:
        provider: script
        cleanup: true
        script: mvn -s .m2/settings.xml clean deploy -Drevision=$NEW_VERSION -Dchangelist=$CHANGELIST
        on:
          all_branches: true
      after_success:
        - if $IS_MASTER; then git tag "$NEW_VERSION" "$TRAVIS_COMMIT" && git push origin "$NEW_VERSION"; fi
